Application/SkillsDashboard/Controllers/PendingSkillExpertRequestsController.cs
using Newtonsoft.Json;
using SkillsDashboard.BusinessEntities;
using SkillsDashboard.Models;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace SkillsDashboard.Controllers
{
    [Authorize(Roles = "SKILLEXPERT")]
    public class PendingSkillExpertRequestsController : SkillsDashboardBaseController
    {
        #region Page level declarations
        HttpClient client;
        string apiBaseURL = ConfigurationManager.AppSettings["APIBaseURL"];
        #endregion

        public PendingSkillExpertRequestsController()
        {
            client = new HttpClient();
            client.BaseAddress = new Uri(apiBaseURL);
            client.DefaultRequestHeaders.Accept.Clear();
            client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
        }

        /// <summary>
        /// Action Result method to load main view for Skill Expert approvals page
        /// </summary>
        /// <returns></returns>
        public ActionResult Index()
        {
            PopulateDropdownValues();
            return View();
        }

        /// <summary>
        /// Method to populate request type dropdown
        /// </summary>
        private void PopulateDropdownValues()
        {
            try
            {
                //Populate request mode
                var RequestMode = GetRequestTypes();
                ViewBag.RequestModeList = new SelectList(RequestMode, "ID", "Name");
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        /// <summary>
        /// API call to get pending skill expert approvals
        /// </summary>
        /// <param name="argRequestType">Request Type</param>
        /// <returns></returns>
        [HttpPost]
        public async Task<ActionResult> GetPendingSkillExpertApprovals(string argRequestType)
        {
            #region Declarations
            PendingSkillExpertApprovals l_Requests = new PendingSkillExpertApprovals();
            PendingSkillExpertApprovalBECollection l_ApprovalBECollection = new PendingSkillExpertApprovalBECollection();
            PendingSkillExpertApprovalsCollection l_ApprovalCollection = new PendingSkillExpertApprovalsCollection();
            string l_skillsURL = string.Empty;
            #endregion


            l_skillsURL = apiBaseURL + "/GetSkillExpertApprovals?argLoggedInUser=" + GetLoggedInUserID() + "&argType=" + argRequestType + "";
            HttpResponseMessage l_SkillsData = await client.GetAsync(l_skillsURL);

            if (l_SkillsData != null && l_SkillsData.IsSuccessStatusCode)
            {
                var l_SkillResponse = l_SkillsData.Content.ReadAsStringAsync().Result;
                l_ApprovalBECollection = JsonConvert.DeserializeObject<PendingSkillExpertApprovalBECollection>(l_SkillResponse);
            }

            l_ApprovalCollection = ConverPendingSkillExpertApprovalsToModel(l_ApprovalBECollection);
            return PartialView("_partialPendingSkillExpertApprovals", l_ApprovalCollection);
        }

        /// <summary>
        /// Method to convert SkillExpertBECollection to Model
        /// </summary>
        /// <param name="argApprovalsBECollection">Business Entity collection for skill expert approval</param>
        /// <returns></returns>
        private PendingSkillExpertApprovalsCollection ConverPendingSkillExpertApprovalsToModel(PendingSkillExpertApprovalBECollection argApprovalsBECollection)
        {
            #region Declarations
            PendingSkillExpertApprovalsCollection l_PendingApprovalsCollection = new PendingSkillExpertApprovalsCollection();
            PendingSkillExpertApprovals l_Approvals;
            #endregion
            try
            {
                if (argApprovalsBECollection != null && argApprovalsBECollection.Count > 0)
                {
                    foreach (var item in argApprovalsBECollection)
                    {
                        l_Approvals = new PendingSkillExpertApprovals();
                        l_Approvals.ManagerComments = item.ManagerComments;
                        l_Approvals.UserComments = item.UserComments;
                        l_Approvals.SkillExpertComments = item.SkillExpertComments;
                        l_Approvals.DemoSchedule = item.DemoSchedule;
                        l_Approvals.Room = item.Room;
                        l_Approvals.Status = item.Status;
                        l_Approvals.RequestedDate = item.RequestedDate;
                        l_Approvals.RequestType = item.RequestType;
                        l_Approvals.SkillName = item.SkillName;
                        l_Approvals.SkillPoints = item.SkillPoints;
                        l_Approvals.SubSkillName = item.SubSkillName;
                        l_Approvals.RequestedBy = item.RequestedBy;
                        l_Approvals.UniqueID = item.UniqueID;
                        l_Approvals.FileGUID = item.FileGUID;
                        l_Approvals.FileName = item.FileName;
                        l_Approvals.RequestCode = item.RequestCode;
                        l_PendingApprovalsCollection.Add(l_Approvals);
                    }
                }
            }
            catch (Exception ex)
            {

                throw ex;
            }

            return l_PendingApprovalsCollection;
        }

        /// <summary>
        /// HTTP POST method to schedule demo by skill expert
        /// </summary>
        /// <param name="argScheduleDemo">Demo Details</param>
        /// <returns></returns>
        [HttpPost]
        public async Task<JsonResult> ScheduleDemo(ScheduleDemo argScheduleDemo)
        {
            #region Declarations
            bool IsSuccess = false;
            HttpResponseMessage l_Message = new HttpResponseMessage();
            #endregion
            if (argScheduleDemo != null)
            {
                l_Message = await SaveDemoToDatabase(argScheduleDemo);
                if (l_Message.IsSuccessStatusCode)
                {
                    IsSuccess = true;
                }
            }

            return Json(IsSuccess, JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        /// This method is used to cal WebAPI to save demo details
        /// </summary>
        /// <param name="argScheduleDemo">Demo details</param>
        /// <returns></returns>
        private async Task<HttpResponseMessage> SaveDemoToDatabase(ScheduleDemo argScheduleDemo)
        {
            #region Declarations
            HttpResponseMessage l_Response = new HttpResponseMessage();
            ScheduleDemoBE l_ScheduleDemoBE = new ScheduleDemoBE();
            string l_ManagerResponseURL = apiBaseURL + "/ScheduleDemo?argLoggedInUser=" + GetLoggedInUserID();
            #endregion

            try
            {
                l_ScheduleDemoBE = ConvertDemoScheduleToBE(argScheduleDemo);

                if (l_ScheduleDemoBE != null)
                {
                    l_Response = await client.PostAsJsonAsync(l_ManagerResponseURL, l_ScheduleDemoBE);
                }
            }
            catch (Exception ex)
            {
                throw ex;
            }

            return l_Response;
        }

        /// <summary>
        /// This method is used to convert Demo Model to business Entity
        /// </summary>
        /// <param name="argScheduleDemo"></param>
        /// <returns></returns>
        private ScheduleDemoBE ConvertDemoScheduleToBE(ScheduleDemo argScheduleDemo)
        {
            ScheduleDemoBE l_ScheduleDemoBE = new ScheduleDemoBE();
            try
            {
                if (argScheduleDemo != null)
                {
                    l_ScheduleDemoBE.Room = argScheduleDemo.Room;
                    l_ScheduleDemoBE.Comments = argScheduleDemo.Comments;
                    l_ScheduleDemoBE.DemoSchedule = argScheduleDemo.DemoSchedule;
                    l_ScheduleDemoBE.UniqueID = argScheduleDemo.UniqueID;
                }
            }
            catch (Exception ex)
            {
                throw ex;
            }
            return l_ScheduleDemoBE;
        }

        /// <summary>
        /// HTTP POST method to save skill expert action (APPROVE/REJECT)
        /// </summary>
        /// <param name="argSkillExpertApproval">Skill Expert approval modal</param>
        /// <returns></returns>
        [HttpPost]
        public async Task<JsonResult> SaveSkillExpertApproval(SkillExpertApproval argSkillExpertApproval)
        {
            #region Declarations
            bool IsSuccess = false;
            HttpResponseMessage l_Message = new HttpResponseMessage();
            #endregion
            if (argSkillExpertApproval != null)
            {
                l_Message = await SaveSkillExpertResponseToDatabase(argSkillExpertApproval);
                if (l_Message.IsSuccessStatusCode)
                {
                    IsSuccess = true;
                }
            }

            return Json(IsSuccess, JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        /// This method is used to cal WebAPI to skill expert approval
        /// </summary>
        /// <param name="argSkillExpertApproval">Skill Expert approval model</param>
        /// <returns></returns>
        private async Task<HttpResponseMessage> SaveSkillExpertResponseToDatabase(SkillExpertApproval argSkillExpertApproval)
        {
            #region Declarations
            HttpResponseMessage l_Response = new HttpResponseMessage();
            SkillExpertApprovalBE l_SkillExpertApprovalBE = new SkillExpertApprovalBE();
            string l_SkillExpertResponseURL = apiBaseURL + "/SaveSkillExpertActionable?argLoggedInUser=" + GetLoggedInUserID();
            #endregion

            try
            {

Application/SkillsDashboard/Views/PendingSkillExpertRequests/Index.cshtml
@{
    ViewBag.Title = "Pending Skill Expert Approvals";
}

<h2>Pending Skill Expert Approvals</h2>

<script src="~/Scripts/moment.min.js"></script>
<script src="~/Scripts/bootstrap-datetimepicker.min.js"></script>
<link href="~/Content/bootstrap-datetimepicker.min.css" rel="stylesheet" />

<div class="confirmation-message">

</div>

<div class="form-group">
    <label for="ddl_skill">Select request type</label>
    @Html.DropDownList("RequestList", ViewBag.RequestModeList as SelectList, "ALL", new { @class = "form-control", @id = "ddl_request" })
</div>

<div id="div_PendingSkillExpertApprovalGrid">

</div>

@Html.Partial("_partialLoader")

<div class="modal" id="modal-schedule-demo" data-backdrop="static">
    <div class="modal-dialog">
        <div class="modal-content">
            <!-- Modal Header -->
            <div class="modal-header">
                <h4 class="modal-title">Schedule Demo</h4>
            </div>
            <!-- Modal body -->
            <div class="modal-body skills-modal-height">
                <fieldset class="skill-model-border">
                    <legend class="skill-model-border">Requestor/ Manager inputs</legend>
                    <div class="row">
                        <div class="col-md-6">
                            <label>Requested By: </label>
                            <span id="lbl_RequestedBy"></span>
                        </div>
                        <div class="col-md-6">
                            <label>Skill: </label>
                            <span id="lbl_Skill"></span>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-md-6">
                            <label>Subskill: </label>
                            <span id="lbl_Subskill"></span>
                        </div>
                        <div class="col-md-6">
                            <label>Points: </label>
                            <span id="lbl_Points"></span>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <label>Requestor Comments: </label>
                            <span id="lbl_RequestorComments"></span>
                        </div>
                        <div class="col-md-6">
                            <label>Manager Comments: </label>
                            <span id="lbl_ManagerComments"></span>
                        </div>
                    </div>
                </fieldset>

                <div class="row form-group">
                    <div class="col-md-6">
                        <label>Room *:</label>
                        <input type="text" id="text_room" class="form-control" maxlength="25" onkeyup="removeValidationFromRoomText();"/>
                        <span id="lbl_CommentRoomError" class="text-danger skill-error" style="display:none;">Please enter room</span>
                    </div>
                </div>
                <div class="row">
                    <div class='col-sm-6'>
                        <div class="form-group">
                            <label>Schedule *:</label>
                            <div class='input-group date' id='datetimepicker'>
                                <input type='text' class="form-control" id="text_schedule"/>
                                <span class="input-group-addon">
                                    <span class="glyphicon glyphicon-calendar"></span>
                                </span>
                            </div>
                            <span id="lbl_CommentScheduleError" class="text-danger skill-error row" style="display:none;">Please select schedule</span>
                        </div>
                    </div>
                    </div>
                        <div class="row form-group">
                            <div class="col-md-12">
                                <label>Please enter Comments *:</label>
                                <textarea class="form-control skill-text-area" id="txt-demo" maxlength="250" onkeyup="removeValidationForScheduleDemo();"></textarea>
                                <span id="lbl_DemoScheduleErrorMessage" class="text-danger skill-error" style="display:none;">Please enter comments</span>
                            </div>
                        </div>
                    </div>

                    <!-- Modal footer -->
                    <div class="modal-footer">
                        <button type="button" id="btn-Approve" class="btn btn-success" onclick="ScheduleDemo()">Schedule</button>
                        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                    </div>
                </div>
            </div>
</div>

<div class="modal" id="modal-skillexpert-approve-request">
    <div class="modal-dialog">
        <div class="modal-content">
            <!-- Modal Header -->
            <div class="modal-header">
                <h4 class="modal-title">Approve/Reject request</h4>
            </div>
            <!-- Modal body -->
            <div class="modal-body skills-modal-height">
                <fieldset class="skill-model-border">
                    <legend class="skill-model-border">Requestor/ Manager inputs</legend>
                    <div class="row">
                        <div class="col-md-6">
                            <label>Requested By: </label>
                            <span id="lbl_ActionableRequestedBy"></span>
                        </div>
                        <div class="col-md-6">
                            <label>Skill: </label>
                            <span id="lbl_ActionableSkill"></span>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-md-6">
                            <label>Subskill: </label>
                            <span id="lbl_ActionableSubskill"></span>
                        </div>
                        <div class="col-md-6">
                            <label>Points: </label>
                            <span id="lbl_ActionablePoints"></span>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <label>Requestor Comments: </label>
                            <span id="lbl_ActionableRequestorComments"></span>
                        </div>
                        <div class="col-md-6">
                            <label>Manager Comments: </label>
                            <span id="lbl_ActionableManagerComments"></span>
                        </div>
                    </div>
                </fieldset>

                <fieldset class="skill-model-border" id="actionable-certificate-upload-details" style="display:none;">
                    <legend class="skill-model-border">Certificate Uploaded</legend>
                    <a href="#PATH#" target="_blank" download="" class="action-file-details"></a>
                </fieldset>

                <fieldset class="skill-model-border" id="actionable-demo-details" style="display:none;">
                    <legend class="skill-model-border">Demo Details</legend>
                    <div class="row">
                        <div class="col-md-6">
                            <label>Demo Schedule: </label>
                            <span id="lbl_DemoSchedule"></span>
                        </div>
                        <div class="col-md-6">
                            <label>Room: </label>
                            <span id="lbl_Room"></span>
                        </div>
                    </div>
                </fieldset>

                <div class="row form-group">
                    <div class="col-md-12">
                        <label>Please enter Comments:</label>
                        <textarea class="form-control skill-text-area" id="actionable-skilltext-area" maxlength="250" onkeyup="removeValidationApproveReject();"></textarea>
                        <span id="lbl_ActionableCommentErrorMessage" class="text-danger" style="display:none;">Please enter comments</span>
                    </div>
                </div>


            </div>

            <!-- Modal footer -->
            <div class="modal-footer">
                <button type="button" id="btn-Approve" class="btn btn-success" onclick="SaveSkillExpertAction('APPROVED')">Approve</button>
                <button type="button" id="btn-Reject" class="btn btn-danger" onclick="SaveSkillExpertAction('REJECTED')">Reject</button>
                <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
            </div>

        </div>
    </div>
</div>

<script src="~/Scripts/DataTables/jquery.dataTables.min.js"></script>
<link href="~/Content/DataTables/css/jquery.dataTables.min.css" rel="stylesheet" />





<script type="text/javascript">
    var URL = {};
    URL["GetPendingSkillExpertApprovals"] = "@Url.Action("GetPendingSkillExpertApprovals", "PendingSkillExpertRequests")";
    URL["ScheduleDemo"] = "@Url.Action("ScheduleDemo", "PendingSkillExpertRequests")";
    URL["SaveSkillExpertApproval"] = "@Url.Action("SaveSkillExpertApproval", "PendingSkillExpertRequests")";

</script>
<script src="~/Scripts/Common.js"></script>
<script src="~/Scripts/PendingSkillExpertApprovals.js"></script>

Application/SkillsDashboard/Views/PendingSkillExpertRequests/_partialPendingSkillExpertApprovals.cshtml
@model SkillsDashboard.Models.PendingSkillExpertApprovalsCollection


<table id="tbl_PendingSkillExpertApprovals">
    <thead>
        <tr>
            <th>Request Type</th>
            <th>Requested By</th>
            <th>Status</th>
            <th>Requested Date</th>
            <th>Requestor Comments</th>
            <th>Manager Comments</th>
            <th>Skill Expert Comments</th>
            <th>Skill</th>
            <th>Subskill</th>
            <th>Skill Points</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
            {
            <tr id="@item.RequestCode-@item.UniqueID">
                <td class="td_RequestType">@item.RequestType</td>
                <td class="td_RequestedBy">@item.RequestedBy</td>
                <td class="td_Status">@item.Status</td>
                <td class="td_RequestedDate">@item.RequestedDate</td>
                <td class="td_UserComments">@item.UserComments</td>
                <td class="td_ManagerComments">@item.ManagerComments</td>
                <td class="td_SkillExpertComments">@item.SkillExpertComments</td>
                <td class="td_SkillName">@item.SkillName</td>
                <td class="td_SubSkillName">@item.SubSkillName</td>
                <td class="td_SkillPoints">@item.SkillPoints</td>
                <td><input type="button" class="btn btn-primary" value="Take Action" onclick="OpenActionPopup('@item.RequestCode-@item.UniqueID')" /></td>

                @Html.Hidden("FileGUID", item.FileGUID, new { @class = item.RequestCode+"-"+ item.UniqueID + "-file-GUID" })
                @Html.Hidden("FileName", item.FileName, new { @class = item.RequestCode + "-" + item.UniqueID + "-file-Name" })
                @Html.Hidden("Room", item.Room, new { @class = item.RequestCode + "-" + item.UniqueID + "-Room" })
                @Html.Hidden("DemoSchedule", item.DemoSchedule, new { @class = item.RequestCode + "-" + item.UniqueID + "-DemoSchedule" })

            </tr>
        }
    </tbody>
</table>