Application/SkillsDashboard/Controllers/DashboardController.cs
using SkillsDashboard.BusinessEntities;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Web;
using System.Web.Mvc;
using SkillsDashboard.Models;
using System.Threading.Tasks;
using Newtonsoft.Json;
using SkillsDashboard.Utilities;
using System.Text;

namespace SkillsDashboard.Controllers
{
    [Authorize]
    public class DashboardController : SkillsDashboardBaseController
    {
        #region Page level declarations
        HttpClient client;
        string apiBaseURL = ConfigurationManager.AppSettings["APIBaseURL"];
        #endregion

        public DashboardController()
        {
            client = new HttpClient();
            client.BaseAddress = new Uri(apiBaseURL);
            client.DefaultRequestHeaders.Accept.Clear();
            client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
        }

        /// <summary>
        /// Action Result method to view dashboard details
        /// </summary>
        /// <param name="argUserID">UserID</param>
        /// <returns></returns>
        public ActionResult Index(int? argUserID)
        {
            int l_UserID = 0;
            try
            {
                if (TempData[SkillConstants.C_INTITIAL_REQUEST_SUCCESS_CONST] != null)
                {
                    ViewBag.SuccessMessage = TempData[SkillConstants.C_INTITIAL_REQUEST_SUCCESS_CONST];
                }

                if (!argUserID.HasValue)
                {
                    l_UserID = GetLoggedInUserID();
                }
                ViewBag.UserID = l_UserID;
            }
            catch (Exception ex)
            {
                throw ex;
            }
            return View();
        }

        /// <summary>
        /// ActionResult method to load dashboard details for a user
        /// </summary>
        /// <param name="argUserID">User ID for whom dashboard details should be loaded</param>
        /// <returns></returns>
        public async Task<ActionResult> GetDashboardDetailsForUser(int argUserID)
        {
            Dashboard l_Dashboard = new Dashboard();
            try
            {
                l_Dashboard = await GetDashboardDetails(argUserID);
            }
            catch (Exception)
            {
                throw;
            }
            return PartialView("_partialDashboardDetails", l_Dashboard);
        }

        /// <summary>
        /// API call to get dashboard details
        /// </summary>
        /// <param name="argUserID">User ID for loading dashboard details</param>
        /// <returns></returns>
        private async Task<Dashboard> GetDashboardDetails(int argUserID)
        {
            #region Declarations
            DashboardBE l_DashboardBE = new DashboardBE();
            Dashboard l_Dashboard = new Dashboard();
            int l_LoggedInUser = 0;
            string l_DashboardURL = string.Empty;
            #endregion

            try
            {
                l_LoggedInUser = GetLoggedInUserID();
                l_DashboardURL = apiBaseURL + "/GetDashboardData?argLoggedInUser=" + l_LoggedInUser+ "&argUserID="+ argUserID;
                HttpResponseMessage l_DashboardData = await client.GetAsync(l_DashboardURL);

                if (l_DashboardData != null && l_DashboardData.IsSuccessStatusCode)
                {
                    var l_DashboardResponse = l_DashboardData.Content.ReadAsStringAsync().Result;
                    l_DashboardBE = JsonConvert.DeserializeObject<DashboardBE>(l_DashboardResponse);
                    l_Dashboard = ConvertDashboardBEDataToModel(l_DashboardBE);
                }

            }
            catch (Exception ex)
            {
                throw ex;
            }
            return l_Dashboard;
        }

        /// <summary>
        /// Convert dashboard business entity to Model
        /// </summary>
        /// <param name="argDashboardBE">Dashboard business Entity</param>
        /// <returns></returns>
        private Dashboard ConvertDashboardBEDataToModel(DashboardBE argDashboardBE)
        {
            #region Declarations
            Dashboard l_Dashboard = new Dashboard();
            SkillCollection l_SkillCollection = new SkillCollection();
            BadgeCollection l_BadgeCollection = new BadgeCollection();
            ScheduleDemoCollection l_ScheduleDemoCollection = new ScheduleDemoCollection();
            Badge l_Badge;
            Skills l_Skills;
            ScheduleDemo l_ScheduleDemo;
            #endregion
            try
            {
                if (argDashboardBE != null)
                {
                    //Get User Details
                    l_Dashboard.UserID = argDashboardBE.UserID;
                    l_Dashboard.UserName = argDashboardBE.UserName;
                    l_Dashboard.EmailID = argDashboardBE.EmailID;
                    l_Dashboard.InitialSkillExists = argDashboardBE.InitialSkillExists;
                    l_Dashboard.DisplayActionItems = argDashboardBE.UserID == GetLoggedInUserID() ? true : false;
                    

                    //Convert Skill and subskill set
                    if (argDashboardBE.SkillsBECollection != null && argDashboardBE.SkillsBECollection.Count > 0)
                    {
                        foreach (var skill in argDashboardBE.SkillsBECollection)
                        {
                            l_Skills = new Skills();
                            l_Skills.SkillID = skill.SkillID;
                            l_Skills.SkillName = skill.SkillName;
                            l_Skills.SkillType = skill.SkillType;
                            l_Skills.SkillPoints = skill.SkillPoints;
                            l_Skills.SubSkillCollection = GetSubskillcollection(skill.SubSkillBECollection);

                            l_SkillCollection.Add(l_Skills);
                        }

                        l_Dashboard.SkillsCollection = l_SkillCollection;

                        
                        l_Dashboard.SkillData = JsonConvert.SerializeObject(l_SkillCollection);
                    }

                    //Convert Badge
                    if (argDashboardBE.BadgeBECollection != null && argDashboardBE.BadgeBECollection.Count > 0)
                    {
                        foreach (var badgeBE in argDashboardBE.BadgeBECollection)
                        {
                            l_Badge = new Badge();
                            l_Badge.BadgeID = badgeBE.BadgeID;
                            l_Badge.BadgeName = badgeBE.BadgeName;
                            l_Badge.BadgeURL = badgeBE.BadgeURL;
                            l_Badge.BadgeCount = badgeBE.BadgeCount;

                            l_BadgeCollection.Add(l_Badge);

                        }

                        l_Dashboard.BadgeCollection = l_BadgeCollection;

                    }

                    //Convert Demo Details
                    if (argDashboardBE.ScheduleDemoBECollection != null && argDashboardBE.ScheduleDemoBECollection.Count > 0)
                    {
                        foreach (var demoBE in argDashboardBE.ScheduleDemoBECollection)
                        {
                            l_ScheduleDemo = new ScheduleDemo();
                            l_ScheduleDemo.DemoSchedule = demoBE.DemoSchedule;
                            l_ScheduleDemo.Comments = demoBE.Comments;
                            l_ScheduleDemo.UniqueID = demoBE.UniqueID;
                            l_ScheduleDemo.Room = demoBE.Room;
                            l_ScheduleDemo.SkillID = demoBE.SkillID;
                            l_ScheduleDemo.SkillName = demoBE.SkillName;
                            l_ScheduleDemo.SubSkillName = demoBE.SubSkillName;
                            l_ScheduleDemo.UserID = demoBE.UserID;
                            l_ScheduleDemo.EventConductedBy = demoBE.EventConductedBy;

                            l_ScheduleDemoCollection.Add(l_ScheduleDemo);
                        }

                        l_Dashboard.ScheduleDemoCollection = l_ScheduleDemoCollection;
                    }
                }
            }
            catch (Exception)
            {
                throw;
            }

            return l_Dashboard;
        }

        /// <summary>
        /// Method to convert subskill model collection from Business Entity
        /// </summary>
        /// <param name="argsubSkillBECollection">Subskill business entity</param>
        /// <returns></returns>
        private SubSkillCollection GetSubskillcollection(SubSkillBECollection argsubSkillBECollection)
        {
            #region Declarations
            SubSkillCollection l_SubSkillCollection = new SubSkillCollection();
            Subskills l_SubSkills;
            #endregion
            try
            {
                if(argsubSkillBECollection!=null && argsubSkillBECollection.Count > 0)
                {
                    foreach (var subskillBE in argsubSkillBECollection)
                    {
                        l_SubSkills = new Subskills();
                        l_SubSkills.SubSkillID = subskillBE.SubSkillID;
                        l_SubSkills.SubSkillName = subskillBE.SubSkillName;
                        l_SubSkills.SkillID = subskillBE.SkillID;
                        l_SubSkills.SkillPoints = subskillBE.SkillPoints;
                        l_SubSkills.SubSkillType = subskillBE.SubSkillType;
                        l_SubSkills.SkillName = subskillBE.SkillName;

                        l_SubSkillCollection.Add(l_SubSkills);
                    }
                    
                }
            }
            catch (Exception)
            {

                throw;
            }

            return l_SubSkillCollection;
        }
    }
}

Application/SkillsDashboard/Controllers/SkillsController.cs
using SkillsDashboard.BusinessEntities;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Web;
using System.Web.Mvc;
using SkillsDashboard.Models;
using System.Threading.Tasks;
using Newtonsoft.Json;
using SkillsDashboard.Utilities;

namespace SkillsDashboard.Controllers
{
    [Authorize]
    public class SkillsController : SkillsDashboardBaseController
    {
        #region Page level declarations
        HttpClient client;
        string apiBaseURL = ConfigurationManager.AppSettings["APIBaseURL"];
        #endregion

        public SkillsController()
        {
            client = new HttpClient();
            client.BaseAddress = new Uri(apiBaseURL);
            client.DefaultRequestHeaders.Accept.Clear();
            client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
        }

        /// <summary>
        /// Main Action Result method to load primary skills page
        /// </summary>
        /// <returns></returns>
        public async Task<ActionResult> Index()
        {
            #region Declarations
            UserInitialSkillRequest l_UserInitialSkillRequest = new UserInitialSkillRequest();
            SkillsBECollection l_SkillsBECollection = new SkillsBECollection();
            #endregion

            var l_Skills = await GetAllSkills();
            ViewBag.SkillList = new SelectList(l_Skills, "SkillID", "SkillName");

            return View(l_UserInitialSkillRequest);
        }

        /// <summary>
        /// Post method to save initial request skill data
        /// </summary>
        /// <param name="argSkillRequest"></param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> SaveIntialSkillRequest(UserInitialSkillRequest argSkillRequest)
        {
            #region Declarations
            HttpResponseMessage l_Message = new HttpResponseMessage();
            #endregion
            if(ModelState.IsValid)
            {
                if(argSkillRequest!=null && argSkillRequest.SubskillCollection!=null && argSkillRequest.SubskillCollection.Count > 0 && argSkillRequest.SubskillCollection.Exists(x=>x.IsSelected == true))
                {
                    //Remove all subskills which are not selected
                    argSkillRequest.SubskillCollection.RemoveAll(x => x.IsSelected == false);

                    l_Message = await SaveInitialSkills(argSkillRequest);

                    if (l_Message.IsSuccessStatusCode)
                    {
                        TempData[SkillConstants.C_INTITIAL_REQUEST_SUCCESS_CONST] = SkillConstants.C_SUCCESS_CONST;
                        return RedirectToAction("Index", "Dashboard");
                    }
                }
                else
                {
                    ViewBag.SkillErrorMessage = "Please select altleast one subskill to proceed";
                }
               
            }
            //Set skill details in viewbag
            var l_Skills = await GetAllSkills();
            ViewBag.SkillList = new SelectList(l_Skills, "SkillID", "SkillName");
            return View("Index", argSkillRequest);
        }

        /// <summary>
        /// API call to save Initial skill requests 
        /// </summary>
        /// <param name="argSkillRequest"></param>
        /// <returns></returns>
        private async Task<HttpResponseMessage> SaveInitialSkills(UserInitialSkillRequest argSkillRequest)
        {
            #region Declarations
            HttpResponseMessage l_Response = new HttpResponseMessage();
            UserInitialSkillRequestBE l_RequestBE = new UserInitialSkillRequestBE();
            string l_SaveSkillURL = apiBaseURL + "/CreateInitialSkillRequest?argLoggedInUser=" + GetLoggedInUserID();
            #endregion

            try
            {
                l_RequestBE = ConvertSkillRequestToBusinessEntity(argSkillRequest);
                if(l_RequestBE!=null)
                {
                    l_Response = await client.PostAsJsonAsync(l_SaveSkillURL, l_RequestBE);
                }
            }
            catch (Exception ex)
            {
                throw ex;
            }

            return l_Response;
        }

        /// <summary>
        /// This method is used to convert Intial Request to business entity
        /// </summary>
        /// <param name="argSkillRequest"></param>
        /// <returns></returns>
        private UserInitialSkillRequestBE ConvertSkillRequestToBusinessEntity(UserInitialSkillRequest argSkillRequest)
        {
            #region Declarations
            UserInitialSkillRequestBE l_UserInitialSkillRequestBE = new UserInitialSkillRequestBE();
            SubSkillBECollection l_SubskillsBECollection = new SubSkillBECollection();
            SubskillsBE l_Subskills;
            #endregion
            try
            {
                if(argSkillRequest!=null)
                {
                    //Comments
                    l_UserInitialSkillRequestBE.Comments = argSkillRequest.Comments;

                    //Subskills
                    if(argSkillRequest.SubskillCollection!=null && argSkillRequest.SubskillCollection.Count > 0)
                    {
                        foreach (var subskills in argSkillRequest.SubskillCollection)
                        {
                            l_Subskills = new SubskillsBE();
                            l_Subskills.SubSkillID = subskills.SubSkillID;
                            l_Subskills.SkillID = subskills.SkillID;
                            l_SubskillsBECollection.Add(l_Subskills);
                        }
                        l_UserInitialSkillRequestBE.UserSubskills = l_SubskillsBECollection;
                    }
                }
            }
            catch (Exception ex)
            {
                throw ex;
            }

            return l_UserInitialSkillRequestBE;
        }

        /// <summary>
        /// Get all subskills on the basis of skill selected
        /// </summary>
        /// <param name="argSkillID"></param>
        /// <returns></returns>
        [HttpPost]
        public async Task<ActionResult> GetSubskills(int argSkillID)
        {
            #region Declarations
            UserInitialSkillRequest l_UserInitialSkillRequest = new UserInitialSkillRequest();
            SubSkillBECollection l_SubSkills = new SubSkillBECollection();
            SubSkillCollection l_SubskillCollection = new SubSkillCollection();
            #endregion

            l_SubSkills = await GetSubskillsForSkill(argSkillID);

            if(l_SubSkills!=null && l_SubSkills.Count > 0)
            {
                l_SubskillCollection = ConvertSubskillCollectionToModel(l_SubSkills);
                l_UserInitialSkillRequest.SubskillCollection = l_SubskillCollection;
            }


            return PartialView("_partialSubskills", l_UserInitialSkillRequest);
        }

       
    }
}

Application/SkillsDashboard/Views/Dashboard/Index.cshtml
@{
    ViewBag.Title = "Index";
}
<script src="~/Scripts/jquery-ui-1.12.1.min.js"></script>
<link href="~/Content/themes/base/jquery-ui.min.css" rel="stylesheet" />
<script src="~/Scripts/Highcharts-4.0.1/js/highcharts.js"></script>

<div class="skill-dashboard-header">
    <div class="form-group">
        <input type="button" class="btn btn-primary skills-dashboard-employee-search" id="btn_LoadEmployeeDetails" value="Search" />

        <input type="text" class="form-control pull-left" id="txt_SearchEmployee"/>
        <span id="lbl_UserTextError" class="text-danger" style="display:none;">Please select user</span>
        
    </div>
</div>

<h2>Dashboard</h2>

<input type="hidden" id="hdn_SearchDashboardFor"/>

@if (ViewBag.SuccessMessage != null)
{
    <div class="alert alert-success">
        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
        Request has been submitted successfully
    </div>
}

<div id="div_dashboardDetails">
    
</div>

@Html.Partial("_partialLoader")

<script type="text/javascript">

    var URL = {};
    URL["GetDashboardDetailsForUser"] = '@Url.Action("GetDashboardDetailsForUser","Dashboard")';
    URL["GetEmployeesByName"] = '@Url.Action("GetEmployeesByName", "Badge")';
    var UserID = '@ViewBag.UserID';

</script>
<script src="~/Scripts/Dashboard.js"></script>

Application/SkillsDashboard/Views/Dashboard/_partialBadgeDetails.cshtml
@model SkillsDashboard.Models.Dashboard

@if(Model!=null && Model.BadgeCollection!=null && Model.BadgeCollection.Count > 0)
{

    <div class="col-md-4">
        <div class="skill-dashboard-container animated pulse">
            <div class="skill-dashboard-icon">

                <img src="~/Images/@Model.BadgeCollection[0].BadgeURL" class="skill-dashboard-badge-image" />
            </div>
            <div class="skill-dashboard-body">
                <span class="skill-dashboard-count">@Model.BadgeCollection[0].BadgeCount</span>
                <span class="skill-dashboard-title">Skill Expert Badges</span>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="skill-dashboard-container user-badge animated pulse">
            <div class="user-badge-icon">
                <img src="~/Images/@Model.BadgeCollection[1].BadgeURL" class="skill-dashboard-badge-image" />
            </div>
            <div class="skill-dashboard-body">
                <span class="skill-dashboard-count">@Model.BadgeCollection[1].BadgeCount</span>
                <span class="skill-dashboard-title">Query Badges</span>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        @if (Model.DisplayActionItems == true)
        {
            if (Model.InitialSkillExists)
            {
                <a href="@Url.Action("Index","ImproveSkills")" target="_blank">
                    <div class="skill-dashboard-container improve-skills animated pulse">
                        <div class="improve-skills-icon">
                            <i class="glyphicon glyphicon-star"></i>
                        </div>
                        <div class="skill-dashboard-body">
                            <span class="skill-dashboard-count">&nbsp;</span>
                            <span class="skill-dashboard-title">Improve Skills</span>
                        </div>

                    </div>
                </a>
            }
            else
            {
                <a href="@Url.Action("Index","Skills")" target="_blank">
                    <div class="skill-dashboard-container improve-skills animated pulse">
                        <div class="improve-skills-icon">
                            <i class="glyphicon glyphicon-star"></i>
                        </div>
                        <div class="skill-dashboard-body">
                            <span class="skill-dashboard-count">&nbsp;</span>
                            <span class="skill-dashboard-title">Add Primary Skills</span>
                        </div>
                    </div>
                </a>
            }
        }
      </div>
  }

Application/SkillsDashboard/Views/Dashboard/_partialDashboardDetails.cshtml
@model SkillsDashboard.Models.Dashboard


<div class="container">
    <div class="row">
        @{
            Html.RenderPartial("_partialUserProfileDetails");
        }

        <div class="col-md-8 col-sm-12 col-xs-12">
            <div id="skills_chartContainer">
                @{
                    Html.RenderPartial("_partialSkillChart");
                }
            </div>
        </div>
    </div>

    <div class="row">
        @{
            Html.RenderPartial("_partialBadgeDetails");
        }
    </div>

    @if (Model.DisplayActionItems == true)
    {
        <div class="row">
            @{
                Html.RenderPartial("_partialDemoDetails");
            }
        </div>
    }
</div>



    

Application/SkillsDashboard/Views/Dashboard/_partialDemoDetails.cshtml
@model SkillsDashboard.Models.Dashboard

<div class="col-md-4">
    <div class="skills-event-container">
        <div class="skills-event-header">
            <span class="skill-event-title">Event Notifications</span>
        </div>

        <div class="skill-event-container-body">

            @if (Model != null && Model.ScheduleDemoCollection != null && Model.ScheduleDemoCollection.Count > 0)
            {
                <ul class="skill-notification-list">
                    @foreach (var demoDetails in Model.ScheduleDemoCollection)
                    {
                        <li><a class="skill-notification-title" href="">Skill: @demoDetails.SkillName (@demoDetails.SubSkillName)</a><p>Demo on @demoDetails.SubSkillName (@demoDetails.SkillName) by @demoDetails.EventConductedBy on @demoDetails.DemoSchedule at @demoDetails.Room</p></li>
                    }
                </ul>
            }
            else
            {
                <p>No Demo Scheduled</p>
            }

        </div>
    </div>
</div>
<script src="~/Scripts/jquery.easy-ticker.min.js"></script>
<script type="text/javascript">
    $('.skill-event-container-body').easyTicker({
        direction: 'up'
    });
</script>

Application/SkillsDashboard/Views/Dashboard/_partialSkillChart.cshtml
@model SkillsDashboard.Models.Dashboard


<script type="text/javascript">

    var skillSetDataResponse = '@Model.SkillData';
    var skillSetData = JSON.parse(skillSetDataResponse.replace(/&quot;/g, '"'));
    var requiredSkillSets = [];
    var acquiredSkillSets = [];
    var skillNames = [];

    //Get the values from skill JSON
    for (var i = 0; i < skillSetData.length; i++) {

        //Create arra for required and acquired skills

        if (skillSetData[i].SkillType.toUpperCase() == 'REQUIRED') {
            requiredSkillSets.push({ y: skillSetData[i].SkillPoints, 'SubskillData': skillSetData[i].SubSkillCollection }); //Required skills
        }
        else {
            acquiredSkillSets.push({ y: skillSetData[i].SkillPoints, 'SubskillData': skillSetData[i].SubSkillCollection }); //Acquired skills
        }

        if ($.inArray(skillSetData[i].SkillName, skillNames) < 0) {
            skillNames.push(skillSetData[i].SkillName); //SkillName array
        }
    }

    var chart = new Highcharts.Chart({

        chart: {
            type: 'column',
            renderTo: 'skills_chartContainer'
        },

        title: {
            text: 'Skill Chart'
        },

        subtitle: {
            text: 'Required and acquired points for your skill(s)'
        },

        legend: {
            align: 'right',
            verticalAlign: 'middle',
            layout: 'vertical'
        },

        xAxis: {
            categories: skillNames,
            labels: {
                x: -10
            },
            title: {
                text: 'Skills'
            }
        },
        tooltip: {
            formatter: function () {
                var tooltip;
                var subSkillToolTipData = this.point.SubskillData;
                if (this.name == "Required") {
                    tooltip = '<b>Points for ' + this.x + ': </b>' + this.y + '<br>';
                }
                else {
                    tooltip = '<b>Points for ' + this.x + ': </b>' + this.y + '<br>';
                }

                if (subSkillToolTipData != null) {
                    for (var i = 0; i < subSkillToolTipData.length; i++) {
                        tooltip += '<span>' + subSkillToolTipData[i].SubSkillName + '</span>:<span>' + subSkillToolTipData[i].SkillPoints + '</span><br>';
                    }
                }
                return tooltip;
            }
        },

        yAxis: {
            allowDecimals: false,
            title: {
                text: 'Points'
            }
        },

        series: [{
            name: 'Required',
            data: requiredSkillSets
        },
        {
            name: 'Acquired',
            data: acquiredSkillSets
        }],

        responsive: {
            rules: [{
                condition: {
                    maxWidth: 1000
                },
                chartOptions: {
                    legend: {
                        align: 'center',
                        verticalAlign: 'bottom',
                        layout: 'horizontal'
                    },
                    yAxis: {
                        labels: {
                            align: 'left',
                            x: 0,
                            y: -5
                        },
                        title: {
                            text: null
                        }
                    },
                    subtitle: {
                        text: null
                    },
                    credits: {
                        enabled: false,
                    }
                }
            }]
        }
    });

</script>

Application/SkillsDashboard/Views/Dashboard/_partialUserProfileDetails.cshtml
@model SkillsDashboard.Models.Dashboard

<div class="skill-dashboard-user-profile">
    <div class="col-md-4 col-sm-12 col-xs-12">
        <div class="skill-dashboard-profile-container">
            <div class="skill-dashboard-profile-bg">

            </div>
            <div class="profile-avatar-image">
                <img src="~/Images/avatar_male.png">
            </div>
            <div class="skill-dashboard-profile-description">
                <h5>@Model.UserName</h5>
                <p>@Model.EmailID</p>
            </div>

        </div>
    </div>
</div>