Application/SkillsDashboard/Controllers/PendingManagerRequestsController.cs
using Newtonsoft.Json;
using SkillsDashboard.BusinessEntities;
using SkillsDashboard.Models;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace SkillsDashboard.Controllers
{
    [Authorize(Roles = "MANAGER")]
    public class PendingManagerRequestsController : SkillsDashboardBaseController
    {
        #region Page level declarations
        HttpClient client;
        string apiBaseURL = ConfigurationManager.AppSettings["APIBaseURL"];
        #endregion

        public PendingManagerRequestsController()
        {
            client = new HttpClient();
            client.BaseAddress = new Uri(apiBaseURL);
            client.DefaultRequestHeaders.Accept.Clear();
            client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
        }

        /// <summary>
        /// Action Result method to load main view for Manager approvals page
        /// </summary>
        /// <returns></returns>
        public ActionResult Index()
        {
            PopulateDropdownValues();
            return View();
        }

        /// <summary>
        /// Method to populate request type dropdown
        /// </summary>
        private void PopulateDropdownValues()
        {
            try
            {
                //Populate request mode
                var RequestMode = GetRequestTypes(true);
                ViewBag.RequestModeList = new SelectList(RequestMode, "ID", "Name");
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        /// <summary>
        /// API call to fetch pending manager approvals 
        /// </summary>
        /// <param name="argRequestType">Request Type</param>
        /// <returns></returns>
        [HttpPost]
        public async Task<ActionResult> GetPendingManagerApprovals(string argRequestType)
        {
            #region Declarations
            PendingManagerApprovals l_Requests = new PendingManagerApprovals();
            PendingManagerApprovalsBECollection l_ApprovalBECollection = new PendingManagerApprovalsBECollection();
            PendingManagerApprovalCollection l_ApprovalCollection = new PendingManagerApprovalCollection();
            string l_skillsURL = string.Empty;
            #endregion


            l_skillsURL = apiBaseURL + "/GetManagerApprovals?argLoggedInUser=" + GetLoggedInUserID() + "&argType=" + argRequestType + "";
            HttpResponseMessage l_SkillsData = await client.GetAsync(l_skillsURL);

            if (l_SkillsData != null && l_SkillsData.IsSuccessStatusCode)
            {
                var l_SkillResponse = l_SkillsData.Content.ReadAsStringAsync().Result;
                l_ApprovalBECollection = JsonConvert.DeserializeObject<PendingManagerApprovalsBECollection>(l_SkillResponse);
            }

            l_ApprovalCollection = ConverMendingManagerApprovalsToModel(l_ApprovalBECollection);
            return PartialView("_partialPendingManagerApprovals", l_ApprovalCollection);
        }

        /// <summary>
        /// Method to convert ManagerApproval business entity to model
        /// </summary>
        /// <param name="argApprovalsBECollection"></param>
        /// <returns></returns>
        private PendingManagerApprovalCollection ConverMendingManagerApprovalsToModel(PendingManagerApprovalsBECollection argApprovalsBECollection)
        {
            #region Declarations
            PendingManagerApprovalCollection l_PendingApprovalsCollection = new PendingManagerApprovalCollection();
            PendingManagerApprovals l_Approvals;
            #endregion
            try
            {
                if (argApprovalsBECollection != null && argApprovalsBECollection.Count > 0)
                {
                    foreach (var item in argApprovalsBECollection)
                    {
                        l_Approvals = new PendingManagerApprovals();
                        l_Approvals.Comments = item.Comments;
                        l_Approvals.Status = item.Status;
                        l_Approvals.RequestedDate = item.RequestedDate;
                        l_Approvals.RequestType = item.RequestType;
                        l_Approvals.SkillName = item.SkillName;
                        l_Approvals.SkillPoints = item.SkillPoints;
                        l_Approvals.SubSkillName = item.SubSkillName;
                        l_Approvals.RequestedBy = item.RequestedBy;
                        l_Approvals.UniqueID = item.UniqueID;
                        l_Approvals.FileGUID = item.FileGUID;
                        l_Approvals.FileName = item.FileName;
                        l_Approvals.RequestCode = item.RequestCode;

                        l_Approvals.BadgeGivenFor = item.BadgeGivenFor;
                        l_Approvals.BadgeID = item.BadgeID;
                        l_Approvals.BadgeName = item.BadgeName;
                        l_Approvals.BadgeImageURL = item.BadgeImageURL;

                        l_PendingApprovalsCollection.Add(l_Approvals);
                    }
                }
            }
            catch (Exception ex)
            {

                throw ex;
            }

            return l_PendingApprovalsCollection;
        }

        /// <summary>
        /// Ajax post request to get manager approval data
        /// </summary>
        /// <param name="argManagerApproval"></param>
        /// <returns></returns>
        [HttpPost]
        public async Task<JsonResult> SaveManagerApproval(ManagerApproval argManagerApproval)
        {
            #region Declarations
            bool IsSuccess = false;
            HttpResponseMessage l_Message = new HttpResponseMessage();
            #endregion
            if(argManagerApproval!=null)
            {
                l_Message = await SaveManagerResponseToDatabase(argManagerApproval);
                if(l_Message.IsSuccessStatusCode)
                {
                    IsSuccess = true;
                }
            }

            return Json(IsSuccess, JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        /// This method is used to cal WebAPI to save manager approval
        /// </summary>
        /// <param name="argManagerApproval"></param>
        /// <returns></returns>
        private async Task<HttpResponseMessage> SaveManagerResponseToDatabase(ManagerApproval argManagerApproval)
        {
            #region Declarations
            HttpResponseMessage l_Response = new HttpResponseMessage();
            ManagerApprovalBE l_ManagerApprovalBE = new ManagerApprovalBE();
            string l_ManagerResponseURL = apiBaseURL + "/SaveManagerActionable?argLoggedInUser=" + GetLoggedInUserID();
            #endregion

            try
            {
                l_ManagerApprovalBE = ConvertManagerApprovalToBE(argManagerApproval);

                if(l_ManagerApprovalBE!=null)
                {
                    l_Response = await client.PostAsJsonAsync(l_ManagerResponseURL, l_ManagerApprovalBE);
                }
            }
            catch (Exception ex)
            {
                throw ex;
            }

            return l_Response;
        }

        /// <summary>
        /// This method is used to convert ManagerApproval modal to business entity
        /// </summary>
        /// <param name="argManagerApproval"></param>
        /// <returns></returns>
        private ManagerApprovalBE ConvertManagerApprovalToBE(ManagerApproval argManagerApproval)
        {
            ManagerApprovalBE l_ManagerApprovalBE = new ManagerApprovalBE();
            try
            {
                if (argManagerApproval != null)
                {
                    l_ManagerApprovalBE.Status = argManagerApproval.Status;
                    l_ManagerApprovalBE.Comments = argManagerApproval.Comments;
                    l_ManagerApprovalBE.Type = argManagerApproval.Type;
                    l_ManagerApprovalBE.UniqueID = argManagerApproval.UniqueID;

                }
            }
            catch (Exception ex)
            {
                throw ex;
            }
            return l_ManagerApprovalBE;
        }

        /// <summary>
        /// HTTP POST method to save manager action (approve/reject) for badge
        /// </summary>
        /// <param name="argSaveBadge"></param>
        /// <returns></returns>
        [HttpPost]
        public async Task<JsonResult> SaveManagerApprovalForBadge(SaveBadge argSaveBadge)
        {
            #region Declarations
            bool IsSuccess = false;
            HttpResponseMessage l_Message = new HttpResponseMessage();
            #endregion
            if (argSaveBadge != null)
            {
                l_Message = await SaveBadgeResponseToDatabase(argSaveBadge);
                if (l_Message.IsSuccessStatusCode)
                {
                    IsSuccess = true;
                }
            }

            return Json(IsSuccess, JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        /// API call to save badge details
        /// </summary>
        /// <param name="argSaveBadge">Badge Model</param>
        /// <returns></returns>
        private async Task<HttpResponseMessage> SaveBadgeResponseToDatabase(SaveBadge argSaveBadge)
        {
            #region Declarations
            HttpResponseMessage l_Response = new HttpResponseMessage();
            SaveBadgeBE l_SaveBadgeBE = new SaveBadgeBE();
            string l_ManagerBadgeResponseURL = apiBaseURL + "/ApproveBadge?argLoggedInUser=" + GetLoggedInUserID();
            #endregion

            try
            {
                l_SaveBadgeBE = ConvertManagerApprovalBadgeToBE(argSaveBadge);

                if (l_SaveBadgeBE != null)
                {

Application/SkillsDashboard/Views/PendingManagerRequests/Index.cshtml
@{
    ViewBag.Title = "Pending Manager Approvals";
}

<h2>Pending Manager Approvals</h2>

<div class="confirmation-message">

</div>

<div class="form-group">
    <label for="ddl_skill">Select request type</label>
    @Html.DropDownList("RequestList", ViewBag.RequestModeList as SelectList, "ALL", new { @class = "form-control", @id = "ddl_request" })
</div>

<div id="div_PendingManagerApprovalGrid">

</div>

<div class="modal" id="modal-approve-badge">
    <div class="modal-dialog">
        <div class="modal-content">
            <!-- Modal Header -->
            <div class="modal-header">
                <h4 class="modal-title">Approve/Reject Badge</h4>
            </div>
            <!-- Modal body -->
            <div class="modal-body">
                <div class="row" style="text-align:center;">
                    <img src="#IMGSRC#" id="img_Badge"/>
                </div>
                    <div class="row">
                        <div class="col-md-6">
                            <label>Requested By: </label>
                            <span id="lbl_BadgeRequestedBy"></span>
                        </div>
                        <div class="col-md-6">
                            <label>Requested For: </label>
                            <span id="lbl_BadgeRequestedFor"></span>
                        </div>
                    </div>

                    
                    <div class="row">
                        <div class="col-md-12">
                            <label>Requestor Comments: </label>
                            <span id="lbl_RequestorComments"></span>
                        </div>
                    </div>
                

                
                <div class="row form-group">
                    <div class="col-md-12">
                        <label>Please enter Comments:</label>
                        <textarea class="form-control skill-badge-text-area" maxlength="250" onkeyup="removeBadgeValidation();"></textarea>
                        <span id="lbl_BadgeCommentErrorMessage" class="text-danger" style="display:none;">Please enter comments</span>
                    </div>
                </div>


            </div>

            <!-- Modal footer -->
            <div class="modal-footer">
                <button type="button" id="btn-Approve-badge" class="btn btn-success" onclick="SaveBadge('APPROVED')">Approve</button>
                <button type="button" id="btn-Reject-badge" class="btn btn-danger" onclick="SaveBadge('REJECTED')">Reject</button>
                <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
            </div>

        </div>
    </div>
</div>

<div class="modal" id="modal-approve-request">
    <div class="modal-dialog">
            <div class="modal-content">
                <!-- Modal Header -->
                <div class="modal-header">
                    <h4 class="modal-title">Approve/Reject request</h4>
                </div>
                <!-- Modal body -->
                <div class="modal-body">
                    <fieldset class="skill-model-border">
                        <legend class="skill-model-border">Requestor inputs</legend>
                        <div class="row">
                            <div class="col-md-6">
                                <label>Requested By: </label>
                                <span id="lbl_RequestedBy"></span>
                            </div>
                            <div class="col-md-6">
                                <label>Skill: </label>
                                <span id="lbl_Skill"></span>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-md-6">
                                <label>Subskill: </label>
                                <span id="lbl_Subskill"></span>
                            </div>
                            <div class="col-md-6">
                                <label>Points: </label>
                                <span id="lbl_Points"></span>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12">
                                <label>Requestor Comments: </label>
                                <span id="lbl_RequestorComments"></span>
                            </div>
                        </div>
                    </fieldset>

                    <fieldset class="skill-model-border" id="certificate-upload-details" style="display:none;">
                        <legend class="skill-model-border">Certificate Uploaded</legend>
                        <a href="#PATH#" target="_blank" download="" class="file-details"></a>
                    </fieldset>
                    <div class="row form-group">
                        <div class="col-md-12">
                            <label>Please enter Comments:</label>
                            <textarea class="form-control skill-text-area" maxlength="250" onkeyup="removeValidation();"></textarea>
                            <span id="lbl_CommentErrorMessage" class="text-danger" style="display:none;">Please enter comments</span>
                        </div>
                    </div>


                </div>

                <!-- Modal footer -->
                <div class="modal-footer">
                    <button type="button" id="btn-Approve" class="btn btn-success" onclick="SaveManagerAction('APPROVED')">Approve</button>
                    <button type="button" id="btn-Reject" class="btn btn-danger" onclick="SaveManagerAction('REJECTED')">Reject</button>
                    <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                </div>
        
        </div>
    </div>
</div>

@Html.Partial("_partialLoader")

<script src="~/Scripts/DataTables/jquery.dataTables.min.js"></script>
<link href="~/Content/DataTables/css/jquery.dataTables.min.css" rel="stylesheet" />

<script type="text/javascript">
    var URL = {};
    URL["GetPendingManagerApprovals"] = "@Url.Action("GetPendingManagerApprovals", "PendingManagerRequests")";
    URL["SaveManagerApproval"] = "@Url.Action("SaveManagerApproval", "PendingManagerRequests")";
    URL["SaveManagerApprovalForBadge"] = "@Url.Action("SaveManagerApprovalForBadge", "PendingManagerRequests")"
</script>
<script src="~/Scripts/Common.js"></script>
<script src="~/Scripts/PendingManagerApprovals.js"></script>

Application/SkillsDashboard/Views/PendingManagerRequests/_partialPendingManagerApprovals.cshtml
@model SkillsDashboard.Models.PendingManagerApprovalCollection


    <table id="tbl_PendingManagerApprovals">
        <thead>
            <tr>
                <th>Request Type</th>
                <th>Requested By</th>
                <th>Status</th>
                <th>Requested Date</th>
                <th>Comments</th>
                <th>Skill</th>
                <th>Subskill</th>
                <th>Skill Points</th>
                <th>Badge Given For</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr id="@item.RequestCode-@item.UniqueID">
                    <td class="td_RequestType">@item.RequestType</td>
                    <td class="td_RequestedBy">@item.RequestedBy</td>
                    <td class="td_Status">@item.Status</td>
                    <td class="td_RequestedDate">@item.RequestedDate</td>
                    <td class="td_Comments">@item.Comments</td>
                    @if (item.RequestCode == "BADGE")
                    {
                        <td class="td_SkillName">NA</td>
                        <td class="td_SubSkillName">NA</td>
                        <td class="td_SkillPoints">NA</td>
                        <td class="td_BadgeGivenFor">@item.BadgeGivenFor</td>
                    }
                    else
                    {
                        <td class="td_SkillName">@item.SkillName</td>
                        <td class="td_SubSkillName">@item.SubSkillName</td>
                        <td class="td_SkillPoints">@item.SkillPoints</td>
                        <td class="td_BadgeGivenFor">NA</td>
                    }
                    
                    <td><input type="button" class="btn btn-primary" value="Take Action" onclick="OpenActionPopup('@item.RequestCode-@item.UniqueID','@item.RequestCode')"/></td>

                    @Html.Hidden("FileGUID", item.FileGUID,new { @class= item.RequestCode + "-" + item.UniqueID + "-file-GUID" })
                    @Html.Hidden("FileName", item.FileName, new { @class = item.RequestCode + "-" + item.UniqueID + "-file-Name" })

                    @Html.Hidden("BadgeID", item.BadgeID, new { @class = item.RequestCode + "-" + item.UniqueID + "-badge-ID" })
                    @Html.Hidden("BadgeName", item.BadgeName, new { @class = item.RequestCode + "-" + item.UniqueID + "-badge-Name" })
                    @Html.Hidden("BadgeURL", item.BadgeImageURL, new { @class = item.RequestCode + "-" + item.UniqueID + "-badge-URL" })
                    
                </tr>
            }
        </tbody>
    </table>